language: ruby

rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2

gemfile:
  - gemfiles/Gemfile.activemodel-4.1
  - gemfiles/Gemfile.activemodel-4.0
  - gemfiles/Gemfile.activemodel-3.2.x

matrix:
  exclude:
  - rvm: 1.9.2
    gemfile: gemfiles/Gemfile.activemodel-4.0
  - rvm: 1.9.2
    gemfile: gemfiles/Gemfile.activemodel-4.1

script: "echo 'COME ON!' && bundle exec rake spec"
